server:
  port: 3000
  mode: debug

database:
  host: localhost
  port: 5432
  user: myuser
  password: mypassword
  dbname: mydb

notebook:
  namespace: jupyter
  image:
    notebookcpu: gaoxin2020/notebook-tgqs:jupyter-ubuntu-cpu-base
    notebookgpu: 
    vscodecpu: 
    vscodegpu:
  schedule: default-scheduler
  externalIP: 192.168.8.208
  volumes:
    userWorkspace: me-user-workspace
    archives: me-archives
  defaultPort: 3000

  podType: notebook


triton:
  namespace: triton-serving
  externalIP: 192.168.12.121
  images:
    - 192.168.12.121:5005/traning/triton:24.10-py3
    - 192.168.12.121:5005/traning/triton:23.10-py3
  resources:
    cpu:
      small: 2
      medium: 4
      large: 8
    memory:
      small: 4
      medium: 8
      large: 16
    gpu:
      none: 0
      single: 1
      multi: 2
  ports:
    http: [8000, 8080, 8888]
    grpc: [8001, 8081, 8889]
    metrics: [8002, 8082, 8890]
  backend:
    - tensorrt
    - onnx
    - pytorch
  model_repository:
    - /model
    - /models
    - /workspace/models
  logging:
    verbose: [0, 1, 2, 3]
    formats: ["default", "json"]

crds:
  workflow:
    group: argoproj.io
    version: v1alpha1
    plural: workflows
    kind: Workflow
    timeout: 6060242

  tfjob:
    group: kubeflow.org
    version: v1
    plural: tfjobs
    kind: TFJob
    timeout: 6060242

  pytorchjob:
    group: kubeflow.org
    version: v1
    kind: PyTorchJob
    plural: pytorchjobs
    timeout: 172800

# MinIO配置部分
minio:
  endpoint: "127.0.0.1:9000"  # MinIO服务器地址
  accessKey: "minioadmin"     # 访问密钥
  secretKey: "minioadmin"     # 密钥
  useSSL: false               # 是否使用SSL连接